services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: "grafana-clickhouse-datasource" # Plugin ClickHouse

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse

  table:
    container_name: table
    build: ./table
    depends_on:
      - clickhouse
    command: ["python", "populate_db.py"]

  llm:
    container_name: llm
    build: ./LLM
    depends_on:
      - clickhouse
      - table
    command: ["python", "interrogator.py"] # Specifica lo script da eseguire

volumes:
  clickhouse_data:
  clickhouse_logs:
