
FROM fracorco/pyflink:1.18.1-scala_2.12-java11

RUN mkdir -p /opt/flink/usrlib
RUN wget -P /opt/flink/usrlib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.18/flink-sql-connector-kafka-3.2.0-1.18.jar

# RUN wget -P /opt/flink/usrlib https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.7.0/clickhouse-jdbc-0.7.0.jar 

# RUN wget -P /opt/flink/usrlib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-jdbc-driver-bundle/1.18.1/flink-sql-jdbc-driver-bundle-1.18.1.jar

# RUN wget -P /opt/flink/usrlib https://jdbc.postgresql.org/download/postgresql-42.2.29.jre7.jar




COPY . . 

RUN pip install langchain-groq

RUN pip install python-dotenv

RUN pip install clickhouse-connect


CMD ["python", "flinkjob.py"]
