
FROM fracorco/pyflink:1.18.1-scala_2.12-java11

RUN mkdir -p /opt/flink/usrlib
RUN wget -P /opt/flink/usrlib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.18/flink-sql-connector-kafka-3.2.0-1.18.jar

COPY . . 

RUN pip install langchain-groq

RUN pip install python-dotenv


CMD ["python", "flinkjob.py"]
