apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: "ee5wustcp8zr4b"
    jsonData:
      defaultDatabase: nearyou
      port: 9000
      host: clickhouse
      username: default
      tlsSkipVerify: false
    secureJsonData:
      password: pass
